### ISSUE TITLE
Allow to deploy only master or only dev

### ISSUE THREAD

**Issue by l2fprod** [IBM-Bluemix/insurance-toolchain#12]
The current toolchain deploys both dev and prod versions of the app. What if I'm only interested in the master stream?

What if I want to deploy master for all modules but dev for the dashboard as I want to do fixes there?

Instead of deploying master+dev in one toolchain, we could have the option to select which branch to deploy for each module, defaulting to master.

**Comment by l2fprod** [comment]
**Goal**
Less apps to deploy

**Changes**

*Allow to specify the branch name to build*
![image](https://cloud.githubusercontent.com/assets/12746550/21131982/f942cad4-c111-11e6-8e6b-4117c5a30846.png)

Default to master. A user can click the "create toolchain" button in the github page and then the "create" button in the DevOps page to get a working system.

*Less apps in toolchain*
![image](https://cloud.githubusercontent.com/assets/12746550/21132059/599844a4-c112-11e6-9976-3085f8304e4c.png)

and the branch name is shown in pipeline name.

**Comment by l2fprod** [comment]
@uwefassnacht @rvennam 

what do you think of this change?

Still allow us to setup a "dev" and a "prod" pipelines for our own use while making the default configuration simpler for most users who just want to deploy their own demo.

You can try it:
https://console.ng.bluemix.net/devops/setup/deploy/?repository=https%3A//github.com//IBM-Bluemix/insurance-toolchain.git&branch=deploy-one-branch

**Comment by uwefassnacht** [comment]
I think this looks good. Let me try it this week and change the script.
