### ISSUE TITLE
Free Trial comes with only 2 GB runtime memory

### ISSUE THREAD

**Issue by VidyasagarMSC** [IBM-Bluemix/insurance-toolchain#14]
Toolchain seeks 3.2 GB of free memory for deployment. But Bluemix Trial account provides only 2 GB of Runtime + Container memory . Check [pricing](https://www.ibm.com/cloud-computing/bluemix/pricing)

**Comment by l2fprod** [comment]
#12 would help in deploying only half of this. We can also look more closely at the memory used by the individual apps.

**Comment by l2fprod** [comment]
With #12, the deployment is now under 2GB.
