### ISSUE TITLE
Authentication failure in the DEPLOY stage

### ISSUE THREAD

**Issue by leodeppe** [IBM-Bluemix/insurance-toolchain#21]
Hi. I'm seeing an error with both pipelines (bot and dashboard). The BUILD stage was successful, but the erorr below was found on the DEPLOY stage:
******************************************************
Preparing to start the job...
Preparing the build artifacts...
cf login -a "https://api.eu-gb.bluemix.net" -u "" -p "" -o "" -s "" 
API endpoint: https://api.eu-gb.bluemix.net

Email> 
Password> stty: 'standard input': Inappropriate ioctl for device

stty: 'standard input': Inappropriate ioctl for device
Authenticating...
Credentials were rejected, please try again.

Password> stty: 'standard input': Inappropriate ioctl for device

stty: 'standard input': Inappropriate ioctl for device
Authenticating...
Credentials were rejected, please try again.

Password> stty: 'standard input': Inappropriate ioctl for device

stty: 'standard input': Inappropriate ioctl for device
Authenticating...
Credentials were rejected, please try again.

API endpoint:   https://api.eu-gb.bluemix.net (API version: 2.106.0)
Not logged in. Use 'cf login' to log in.
FAILED
Unable to authenticate.

Finished: FAILED
******************************************************

**Comment by l2fprod** [comment]
added missing api_key https://github.com/IBM-Cloud/insurance-toolchain/pull/22

**Comment by l2fprod** [comment]
@leodeppe 

the commit above should fix the issue

you can
1/ recreate the toolchain from scratch
2/ or edit the configuration of the bot deploy stage, and set API key, org and space

The DEPLOY for dashboard should have worked. What error do you get for the dashboard?

**Comment by leodeppe** [comment]
Hi, Frederic
I tried it again with a fresh environment. The authentication went fine, but I'm having a different error now:
***************************************************************
Invoking 'cf create-service conversation free insurance-bot-conversation'...

Creating service instance insurance-bot-conversation in org ********************** / space dev as **********************...
FAILED
Server error, status code: 502, error code: 10001, message: Service broker error: No matching deployments for the given plan_id.

**Comment by l2fprod** [comment]
@leodeppe 

could you post the full log?
also in which region are you deploying?

**Comment by leodeppe** [comment]
Hi,
I've been deploying in London.
Here's the full log from the bot(master) deploy. The dashboard failed first at the same step (with issues to find the plan_id)
**********************************************************************************
Preparing to start the job...
Preparing the build artifacts...
cf login -a "https://api.eu-gb.bluemix.net" -u apikey -p "****" -o "************@ibm.com" -s "dev" 
API endpoint: https://api.eu-gb.bluemix.net
Authenticating...
OK

Targeted org ************@ibm.com

Targeted space dev



API endpoint:   https://api.eu-gb.bluemix.net (API version: 2.106.0)
User:           ************@ibm.com
Org:            ************@ibm.com
Space:          dev
Login IBM Cloud api=https://api.eu-gb.bluemix.net org=************@ibm.com space=dev
API endpoint: https://api.eu-gb.bluemix.net
Authenticating...
OK

Targeted account IBM (******************************) <-> ******

Targeted resource group Default

Targeted Cloud Foundry (https://api.eu-gb.bluemix.net)

Targeted org ************@ibm.com

Targeted space dev

                      
API endpoint:      https://api.eu-gb.bluemix.net   
Region:            eu-gb   
User:              ***********@ibm.com   
Account:           IBM (*************************) <-> *******  
Resource group:    Default   
CF API endpoint:   https://api.eu-gb.bluemix.net (API version: 2.106.0)   
Org:               ***********@ibm.com   
Space:             dev   
Using manifest file: manifest.yml
Using prefix: 
Invoking 'cf create-service conversation free insurance-bot-conversation'...

Creating service instance insurance-bot-conversation in org ************@ibm.com / space dev as ************@ibm.com...
FAILED
Server error, status code: 502, error code: 10001, message: Service broker error: No matching deployments for the given plan_id.
Invoking 'cf create-service cloudantNoSQLDB Lite insurance-bot-db'...

Creating service instance insurance-bot-db in org ************@ibm.com / space dev as ************@ibm.com...
OK
Invoking 'cf create-service appid Graduated tier insurance-bot-appid'...

Creating service instance insurance-bot-appid in org ************@ibm.com / space dev as ************@ibm.com...
OK

Attention: The plan `Graduated tier` of service `appid` is not free.  The instance `insurance-bot-appid` will incur a cost.  Contact your administrator if you think this is in error.

Invoking 'cf create-service-key insurance-bot-appid for-pipeline'...

Creating service key for-pipeline for service instance insurance-bot-appid as ************@ibm.com...
OK
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 2.19.147.139...
* Connected to appid-management.eu-gb.bluemix.net (2.19.147.139) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 592 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_256_GCM_SHA384
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: wildcard.bluemix.net (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: C=US,ST=New York,L=Armonk,O=International Business Machines Corporation,CN=wildcard.bluemix.net
* 	 start date: Tue, 13 Nov 2018 00:00:00 GMT
* 	 expire date: Fri, 13 Dec 2019 12:00:00 GMT
* 	 issuer: C=US,O=DigiCert Inc,CN=DigiCert SHA2 Secure Server CA
* 	 compression: NULL
* ALPN, server accepted to use http/1.1
> PUT /management/v4/ddb9ebb8-86ac-4984-97b9-69b5eeeaba11/config/idps/cloud_directory HTTP/1.1
> Host: appid-management.eu-gb.bluemix.net
> User-Agent: curl/7.47.0
> Content-Type: application/json
> Accept: application/json
> Authorization: Bearer XXX
> Content-Length: 348
> 
} [348 bytes data]
* upload completely sent off: 348 out of 348 bytes
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< Content-Length: 251
< X-DNS-Prefetch-Control: off
< X-Frame-Options: SAMEORIGIN
< Strict-Transport-Security: max-age=15552000; includeSubDomains
< X-Download-Options: noopen
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Surrogate-Control: no-store
< Cache-Control: no-store, no-cache, must-revalidate, proxy-revalidate
< Pragma: no-cache
< Expires: 0
< ETag: W/"fb-L/KrhCAuwxIpwNaVEr4x8Raqjqw"
< Date: Mon, 19 Nov 2018 09:28:31 GMT
< Connection: keep-alive
< 
{ [251 bytes data]

100   599  100   251  100   348    310    429 --:--:-- --:--:-- --:--:--   429
100   599  100   251  100   348    310    429 --:--:-- --:--:-- --:--:--   429
* Connection #0 to host appid-management.eu-gb.bluemix.net left intact
{"config":{"selfServiceEnabled":true,"interactions":{"identityConfirmation":{"accessMode":"OFF","methods":["email"]},"welcomeEnabled":false,"resetPasswordEnabled":false,"resetPasswordNotificationEnable":false},"identityField":"email"},"isActive":true}Invoking 'cf app insurance-toolchain-20181119092625848-webui'...

Showing health and status for app insurance-toolchain-20181119092625848-webui in org ************@ibm.com / space dev as ************@ibm.com...

App insurance-toolchain-20181119092625848-webui not found
FAILED
Invoking 'cf push insurance-toolchain-20181119092625848-webui -n insurance-toolchain-20181119092625848-webui -f manifest.yml --no-start'...

Pushing from manifest to org ************@ibm.com / space dev as ************@ibm.com...
Using manifest file manifest.yml
Getting app info...
Service instance insurance-bot-conversation not found
FAILED
Invoking 'cf start insurance-toolchain-20181119092625848-webui'...

Starting app insurance-toolchain-20181119092625848-webui in org ************@ibm.com / space dev as ************@ibm.com...
App insurance-toolchain-20181119092625848-webui not found
FAILED

Finished: FAILED

**Comment by l2fprod** [comment]
@leodeppe 

Now I get it

Watson Assistant / Conversation is not available in London (eu-gb):

![image](https://user-images.githubusercontent.com/12746550/48698690-03977e00-ebe8-11e8-8e49-e21388fb8115.png)

**Comment by l2fprod** [comment]
closing this one - please open another issue if anything goes wrong while deploying to another location (like Dallas, or Frankfurt)
