### ISSUE TITLE
Add bot URL to the dashboard as an env variable

### ISSUE THREAD

**Issue by rvennam** [IBM-Bluemix/insurance-toolchain#4]
Dashboard needs the URL of the bot:

`socket_url  : process.env.SOCKET_URL || 'dev-cloudco.mybluemix.net',`

This task is for the toolchain to inject this env var

**Comment by l2fprod** [comment]
changes pushed to https://github.com/IBM-Bluemix/insurance-toolchain/tree/socket_url but waiting on changes done for the readme to be merged before submitting PR for this one
