### ISSUE TITLE
Make name of deployed apps unique

### ISSUE THREAD

**Issue by uwefassnacht** [IBM-Bluemix/insurance-toolchain#8]
When creating the toolchain, "standard names" for the 4 microservices are chose. 

There is no warning to users if these routes are already taken. Errors can be found in the logs:

   `The route dev-cloudco-insurance-catalog.mybluemix.net is already in use.`

But these are hard to find or remedy (for novice cloud foundry users)

Is it possible to ask the user for a pre- or suffix for the apps? Or (at the very least) add a prominent note to the README what needs to be done to avoid this situation?

**Comment by l2fprod** [comment]
@uwefassnacht 

We could change these texts to invite the user to give a unique name:
![image](https://cloud.githubusercontent.com/assets/12746550/19292724/f0dcee52-9069-11e6-9c7a-cad0ab58ff47.png)

**Comment by uwefassnacht** [comment]
Is there a way to make it more obvious than that? Almost force the user to input an app name? If not, can we attach his Bluemix ID to the app name as a pre- or suffix?

**Comment by l2fprod** [comment]
@uwefassnacht 

The only "dynamic" input is the toolchain name. DevOps sets it to xxx-timestamp (insurance-toolchain-1233494494 as example). We can reuse this value in our default names:

![image](https://cloud.githubusercontent.com/assets/12746550/19727534/211363cc-9b90-11e6-80b0-45cdcf188a14.png)

However if the user changes the name of the toolchain, the value change gets propagated so the warning text can still be useful.

You can see these changes here:
https://console.ng.bluemix.net/devops/setup/deploy/?repository=https%3A//github.com//IBM-Bluemix/insurance-toolchain.git&branch=warn-for-same-app-names

**Comment by l2fprod** [comment]
put warning and default names using the toolchain generated number.
if you go to the toolchain and click create this ensures unique names.
